exports.newWord = {
  wordList:["BASKING", "BLACKTIP", "BLUE", "BRONZE WHALER", "BULL", "BAMBOO", "CARRIBEAN REEF", "COOKIECUTTER", "FRILLED", "GOBLIN", "GRAY REEF", "GREAT HAMMERHEAD", "GREAT WHITE", "GREENLAND", "LEMON", "LEOPARD", "MAKO", "MEGALADON", "NURSE", "PORBEAGLE", "PORT JACKSON", "SCALLOPED HAMMERHEAD", "SEVENGILL", "SHORTFIN MAKO", "SILKY", "SILVERTIP", "THRESHER", "TIGER", "WHALE", "WHITETIP REEF", "ZEBRA"],
 
 };